services:
  db_mysql:  
    image: mysql:8.0  # or mysql:5.7 for an earlier version
    container_name: mysql_discovery
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3303:3306" 
    # volumes:
    #   - db_data:/var/lib/mysql  

  adminer:
    image: adminer
    restart: always
    ports:
      - "8084:8080"
    depends_on:
      - db_mysql

volumes:
  db_data:                             # Define a named volume for MySQL data persistence
